---

packages:
  - git
  - gcc
  - gcc-c++
  - make
  - gdb
  - automake
  - autoconf
  - libtool
  - pkg-config
  - nasm
  - ccache
  - cmake
  - patch
  - ninja
  - gperf
  - meson
  - sqlite3
  - php
  - awk
  - gnutls
  - gcc13
  - gcc13-c++
  - libuuid-devel
  - libxml2-devel
  - alsa-devel
  - avahi-compat-mDNSResponder-devel
  - libexiv2-devel
  - libbluray-devel
  - lzo-devel
  - libhdhomerun-devel
  - libsamplerate-devel
  - libmpeg2-devel
  - libv4l-devel
  - libavc1394-devel
  - libiec61883-devel
  - dav1d-devel
  - soundtouch-devel
  - libXinerama-devel
  - libXrandr-devel
  - libXv-devel
  - libva-devel
  - libdrm-devel
  - libva-gl-devel
  - libvdpau-devel
  - libcec-devel
  - libass-devel
  - systemd-devel
  - libvpx-devel
  - libbluray-bdj
  - libmp3lame-devel
  - python3-mysqlclient
  - python3-lxml
  - python3-urlgrabber
  - python3-requests
  - python3-setuptools
  - python3-oauth2
  - perl-ExtUtils-MakeMaker
  - perl-DBI
  - perl-DBD-mysql
  - perl-HTTP-Message
  - perl-libwww-perl
  - perl-IO-Socket-INET6
  - perl-Date-Manip
  - perl-XML-Simple
  - perl-XML-XPath
  - perl-DateTime-Format-ISO8601
  - perl-SOAP-Lite
  - perl-JSON
  - perl-Image-Size
  - perl-Net-UPnP
  - perl(FindBin)
  - perl(IPC::Cmd)
  - libvorbis-devel
  - flac-devel
  - libtag-devel
  - libcdio-devel
  - libcdio-paranoia-devel
  - libmysqlclient-devel
  - fftw3-threads-devel
  - libexif-devel
  - dcraw
  - minizip-devel
  - libzip-devel

qt5_packages:
  - libqt5-qtbase-devel
  - libqt5-qtscript-devel
  - libQt5WebKit5-devel
  - libQt5WebKitWidgets-devel
  - libQt5Sql5-mysql

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=4:
