---

extends: default

rules:

  braces:
    level: warning
    max-spaces-inside: 1
    min-spaces-inside: 0

  colons:
    level: warning
    max-spaces-after: 16
    max-spaces-before: 0

  commas:
    level: warning
    max-spaces-after: 16
    max-spaces-before: 0

  comments:
    min-spaces-from-content: 1

  comments-indentation: false

  document-end: disable

  empty-values: disable

  key-ordering: disable

  # Just warn for long lines
  line-length:
    level: warning
    max: 255

  octal-values: enable

  # Ansible likes yes/no, so don't whine about them
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
