#
# YML host files require Ansible >= 2.1.
#
# This file is used by the mythtv.yml playbook.

---

mythtv_hosts:

  vars:
    ansible_connection: local
    ansible_host: localhost
    mythtv_builders: false
    mythtv_tools: false
    qt6: false

  hosts:
    localhost:
    f30:
      ansible_python_interpreter: /usr/bin/python3
    freebsd:
      ansible_python_interpreter: /usr/local/bin/python2.7
    macosx:
      ansible_pkg_mgr:
        homebrew:
          ansible_python_interpreter: ${HOMEBREW_PREFIX}/bin/python3
        macports:
          ansible_python_interpreter: /opt/local/bin/python3
    builder:
      mythtv_builders: true
      tags: never
    tools:
      mythtv_tools: true
      tags: never

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=4:
