#
# YML host files require Ansible >= 2.1.
#
# mythtv_hosts is used by mythtv.yml and this file is defined in ansible.cfg.

---

mythtv_hosts:

  vars:
    ansible_connection: local
    ansible_host: localhost
    mythtv_builders: false
    mythtv_tools: false
    qt6: false

  hosts:
    localhost:
    libexec:
      ansible_python_interpreter: /usr/libexec/platform-python
    f30:
      ansible_python_interpreter: /usr/bin/python3
    freebsd:  # If sudo isn't installed on the host
      ansible_become_method: su
      use_old_roles: false
    macosx:
      ansible_pkg_mgr:
        homebrew:
          ansible_python_interpreter: ${HOMEBREW_PREFIX}/bin/python3
        macports:
          ansible_python_interpreter: /opt/local/bin/python3
    builder:
      mythtv_builders: true
      tags: never
    tools:
      mythtv_tools: true
      tags: never

    # Here for Docker testing, adjust locally as required.
    172.17.0.1:
    172.17.0.2:
    172.17.0.3:
    172.17.0.4:
    172.17.0.5:

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=4,80:
