#! /usr/bin/env --split-string=ansible-playbook --inventory=hosts.yml
#
# MythTV playbook. Assumes ansible-playbook can be found in $PATH to
# make this executable work:
#
#    ./mythtv.yml --limit=<host>
#
# If not in PATH or env doesn't support --split-string, then run like this:
#
#    ansible-playbook --inventory=hosts.yml --limit=<host> mythtv.yml
#
# <host> = one of the names under hosts: in the hosts.yml file. Most
# will select localhost.

---

- hosts: mythtv_hosts

  roles:
    - role: common

    - role: mythtv-deb
      when:
        - ansible_pkg_mgr == "apt"
        - not mythtv_tools

    - role: mythtv-rpm
      when:
        - ansible_pkg_mgr == "yum"
        - not mythtv_tools

    - role: mythtv-dnf
      when:
        - ansible_pkg_mgr == "dnf"
        - not mythtv_tools

    - role: mythtv-freebsd
      when:
        - ansible_pkg_mgr == "pkgng"
        - not mythtv_tools

    - role: mythtv-macports
      when:
        - ansible_pkg_mgr == "macports"
        - not mythtv_tools

    - role: mythtv-pacman
      when:
        - ansible_pkg_mgr == "pacman"
        - not mythtv_tools

    - role: mythtv-suse
      when:
        - ansible_pkg_mgr == "zypper"
        - not mythtv_tools

    - role: qt5
      when:
        - not mythtv_tools

    - role: buildworker
      when: mythtv_builders

    - role: cppcheck
      when: mythtv_tools

    - role: doxygen
      when: mythtv_tools

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
