#!/usr/bin/env ansible-playbook
#
# MythTV playbook. Assumes ansible-playbook can be found in $PATH to
# make this executable work:
#
#    ./mythtv.yml --limit=<host>
#
# If not, then run like this:
#
#    <your path>/ansible-playbook --limit=<host> mythtv.yml
#
# <host> = one of the names under 'hosts:' in the hosts.yml file. See
# README.md for help.
#
#     Adding: --extra-vars='{"use_old_roles":false}' turns on the new single role
#     Adding: --extra-vars='{"venv_active":true}' builds a Python venv
#

---

- name: 'MythTV'
  hosts: mythtv_hosts

  tasks:

    - include_role:
        name: common

    - include_role:
        name: mythtv
      when:
        - not use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-deb
      when:
        - ansible_pkg_mgr == "apt"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-rpm
      when:
        - ansible_pkg_mgr == "yum"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-dnf
      when:
        - ansible_pkg_mgr in [ "dnf", "dnf5" ]
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-freebsd
      when:
        - ansible_pkg_mgr == "pkgng"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-homebrew
      when:
        - ansible_pkg_mgr == "homebrew"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-macports
      when:
        - ansible_pkg_mgr == "macports"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-pacman
      when:
        - ansible_pkg_mgr == "pacman"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: mythtv-suse
      when:
        - ansible_pkg_mgr == "zypper"
        - use_old_roles
        - not mythtv_tools

    - include_role:
        name: python
      when: not mythtv_tools

    - include_role:
        name: qt5
      when:
        - not mythtv_tools
        - use_old_roles
        - not qt6

    - include_role:
        name: qt6
      when:
        - not mythtv_tools
        - use_old_roles
        - qt6

    - include_role:
        name: buildworker
      when: mythtv_builders

    - include_role:
        name: cppcheck
      when: mythtv_tools

    - include_role:
        name: doxygen
      when: mythtv_tools

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=6:
