---

- name: create list of qt6 libraries
  set_fact:
    yum_pkg_lst:
      - qt6-qtbase-devel
      # packages in repo for fedora, and in epel for centos7/rhel7
      # - none yet
  tags:
    - qt6

# This looks like overkill, but the intent is to provide future maintainers
# with a template to add more (especially conditional) packages.

- name: add qt6 runtime dependencies
  set_fact:
    yum_pkg_lst:
      - '{{ yum_pkg_lst }}'
      - qt6-qtbase-mysql
  tags:
    - qt6

- name: final rpm qt6 package list
  debug:
    msg:
      '{{ lookup("flattened", yum_pkg_lst) }}'

- name: install rpm qt6 packages
  yum:
    name:
      '{{ lookup("flattened", yum_pkg_lst) }}'
    state:
      present
  tags:
    - qt6

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
