---

# parse out database name and major/minor version
# database_version is set in the macports main.yml
- name: qt6-macports | Specify mysql/mariadb database version to compile against
  set_fact:
    qt_mysql_variant: "{{ database_version | regex_replace('-') | regex_replace('\\.', '_') }}"

- name: qt6-macports | Create list of qt6 libraries
  set_fact:
    macports_pkg_list:
      - qt6
      - qt6-qtwebengine
  tags:
    - qt6

- name: qt6-macports | Print final qt6 list of ports
  debug:
    msg:
      '{{ lookup("flattened", macports_pkg_list) }}'

- name: qt6-macports | Install port qt6 packages
  macports:
    name:
      '{{ lookup("flattened", macports_pkg_list) }}'
    update_cache: true
  tags:
    - qt6

- name: qt6-macports | Install qt6-mysql-plugin for previously specified mariadb/mysql version
  macports:
    name: qt6-mysql-plugin
    variant: +{{ qt_mysql_variant }}
  tags:
    - qt6

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
