---

- name: create a list of qt6 libraries
  set_fact:
    zypper_pkg_lst:
      - qt6-base-devel
  tags:
    - qt6

# This looks like overkill, but the intent is to provide future maintainers
# with a template to add more (especially conditional) packages.

- name: add qt6 runtime dependencies
  set_fact:
    zypper_pkg_lst:
      - '{{ zypper_pkg_lst }}'
      - qt6-sql-mysql
  tags:
    - qt6

- name: final zypper qt6 package list
  debug:
    msg:
      '{{ lookup("flattened", zypper_pkg_lst) }}'
  tags:
    - qt6

- name: install zypper qt6 packages
  zypper:
    name:
      '{{ lookup("flattened", zypper_pkg_lst ) }}'
    state:
      present
  tags:
    - qt6

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
