---

- name: qt6-homebrew | Create list of qt6 libraries
  set_fact:
    homebrew_pkg_list:
      - qt@6
      - 'qt-{{ database_name }}'
  tags:
    - qt6

- name: qt6-homebrew | Print final qt6 list of ports
  debug:
    msg:
      '{{ lookup("flattened", homebrew_pkg_list) }}'

- name: qt6-homebrew | Install port qt6 packages
  become: false
  homebrew:
    name:
      '{{ lookup("flattened", homebrew_pkg_list) }}'
  tags:
    - qt6

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
