# Install Qt6

---

- name: create a list of deb qt6 packages
  set_fact:
    deb_pkg_lst:
      - qt6-base-dev
#      - libqt6opengl6-dev

# This looks like overkill, but the intent is to provide future maintainers
# with a template to add more (especially conditional) packages.

- name: add the qt6 mythtv essential runtime libraries
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libqt6sql6-mysql

- name: final deb qt6 package list
  debug:
    msg:
      '{{ lookup("flattened", deb_pkg_lst) }}'

- name: install deb qt6 packages
  apt:
    name:
      '{{ lookup("flattened", deb_pkg_lst ) }}'
    state: present

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
