# roles/buildworker/tasks/main.yml

---

- name: Install python twisted - Fedora
  package:
    name:
      - python-twisted
    state:
      present
  when: ansible_distribution == "Fedora"

- name: Install python twisted - CentOS
  package:
    name:
      - python-twisted-core
      - python-twisted-web
      - python-twisted-words
    state:
      present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

- name: Ensure cron installed - Fedora
  package:
    name:
      - cronie
    state:
      present
  when: ansible_distribution == "Fedora"

# no buildbot in centos7 or epel7...
- name: Install buildworker (rpm)
  package:
    name:
      - buildbot-worker
    state:
      present
  when: ansible_distribution == "Fedora"

- include_tasks: buildbot-build-centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

- include_tasks: buildbot-build-centos8.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 8

- name: Install buildworker (deb)
  apt:
    name:
      - buildbot-worker
    state:
      present
  when: ansible_pkg_mgr == "apt"

- name: Install buildworker (pacman)
  pacman:
    name:
      - buildbot-worker
    state:
      present
  when: ansible_pkg_mgr == "pacman"

- name: Install buildslave from ports
  portinstall:
    name:
      - devel/buildbot-slave
    state:
      present
  when: ansible_distribution == "FreeBSD" and ansible_distribution_major_version|int <= 9

- name: Install buildbot-worker
  pkgng:
    name:
      - py27-buildbot-worker
    state:
      present
  when:
    - ansible_distribution == "FreeBSD"
    - ansible_distribution_major_version|int >= 10
    - ansible_distribution_major_version|int <= 12

- name: Install buildbot-worker
  pkgng:
    name:
      - py37-buildbot-worker
    state:
      present
  when:
    - ansible_distribution == "FreeBSD"
    - ansible_distribution_major_version|int >= 13

- name: Buildbot worker support libraries
  pkgng:
    name:
      - py27-service_identity
    state:
      present
  when:
    - ansible_distribution == "FreeBSD"
    - ansible_distribution_major_version|int <= 12

- name: Buildbot worker support libraries
  pkgng:
    name:
      - py37-service_identity
    state:
      present
  when:
    - ansible_distribution == "FreeBSD"
    - ansible_distribution_major_version|int >= 13

- name: Create buildworker user
  user:
    name: buildworker
    state: present
    generate_ssh_key: yes

- name: Setup ccache max cache size
  command: su - buildworker -c 'ccache -M 10G'

- name: Create buildworker ~/bin
  command: su - buildworker -c 'test -d ~/bin || mkdir ~/bin'

- name: Create buildworker ~/bin
  command: su - buildworker -c 'test -d ~/mythtv || mkdir ~/mythtv'

- name: Install worker startup script
  copy:
    src: '{{ ansible_distribution }}-start-buildworker.sh'
    dest: ~buildworker/bin/start-buildworker.sh
    mode: u=rwx,go=rx
    owner: buildworker

- cron:
    name: "autostart worker at reboot"
    user: buildworker
    special_time: reboot
    job: "$HOME/bin/start-buildworker.sh"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
