# roles/mythtv-rpm/vars/main.yml

---

rpm_url: "https://mirrors.rpmfusion.org"
rpmfusion_rpm: "{{ rpm_url }}/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
rpmfusion_rawhide_rpm: "{{ rpm_url }}/free/fedora/rpmfusion-free-release-rawhide.noarch.rpm"
rpmfusion_el_rpm: "{{ rpm_url }}/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

...
