# roles/buildslave/tasks/main.yml

- name: install python twisted - Fedora
  yum:
    name:
      - python-twisted
    state:
      present
  when: ansible_distribution == "Fedora"

- name: install python twisted - CentOS
  yum:
    name:
      - python-twisted-core
      - python-twisted-web
      - python-twisted-words
    state:
      present
  when: ansible_distribution == "CentOS"

- name: ensure cron installed - Fedora
  yum:
    name:
      - cronie
    state:
      present
  when: ansible_distribution == "Fedora"

# no buildbot in centos7 or epel7...
- name: install buildslave (rpm)
  yum:
    name:
      - buildbot-slave
    state:
      present
  when: ansible_distribution == "Fedora"

- include: buildbot-build.yml
  when: ansible_distribution == "CentOS"

- name: install buildslave (deb)
  apt:
    name:
      - buildbot-slave
    state:
        present
  when: ansible_pkg_mgr == "apt"

- name: install buildslave (pacman)
  pacman:
    name:
      - buildbot-slave
    state:
      present
  when: ansible_pkg_mgr == "pacman"

- name: install buildslave from ports
  portinstall:
    name:
      - devel/buildbot-slave
    state:
      present
  when: ansible_distribution == "FreeBSD" and ansible_distribution_major_version|int <= 9

- name: install buildbot-worker
  pkgng:
    name:
      - py27-buildbot-worker
    state:
      present
  when: ansible_distribution == "FreeBSD" and ansible_distribution_major_version|int >= 10

- name: buildbot worker support libraries
  pkgng:
    name:
      - py27-service_identity
    state:
      present
  when: ansible_distribution == "FreeBSD"

- name: create buildslave user
  user: name=buildslave state=present generate_ssh_key=yes

- name: setup ccache max cache size
  command: su - buildslave -c 'ccache -M 10G'

- name: create buildslave ~/bin
  command: su - buildslave -c 'test -d ~/bin || mkdir ~/bin'

- name: create buildslave ~/bin
  command: su - buildslave -c 'test -d ~/mythtv || mkdir ~/mythtv'

- name: install slave startup script
  copy: src={{ ansible_distribution }}-start-buildslave.sh dest=~buildslave/bin/start-buildslave.sh mode=0755 owner=buildslave

- cron: name="autostart slave at reboot" user=buildslave special_time=reboot job=$HOME/bin/start-buildslave.sh

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
