---

- include_tasks:  pip-macOS.yaml
  when: (ansible_pkg_mgr == "homebrew") or
    (ansible_pkg_mgr == "macports")

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
