---

- name: create a list of required python packages
  set_fact:
    python_pkg_list:
      - lxml
      - mysqlclient
      - oauth
      - pip>=23.0.1
      - pycurl
      - requests
      - requests-cache
      - setuptools
      - urllib3
      - wheel

- name: add optional python packages
  set_fact:
    python_pkg_list:
      - '{{ python_pkg_list }}'
      - argparse
      - audiofile
      - bs4
      - common
      - configparser
      - cryptography
      - datetime
      - discid
      - et
      - features
      - HTMLParser
      - httplib2
      - importlib_metadata
      - markupsafe
      - musicbrainzngs
      - oauthlib
      - python_dateutil
      - simplejson
      - traceback2

- name: print final list of python packages
  debug:
    msg:
      '{{ lookup("flattened", python_pkg_list) }}'

- include_tasks:  pip-macOS.yaml
  when: (ansible_pkg_mgr == "homebrew") or
    (ansible_pkg_mgr == "macports")

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
