# Included by: roles/python/tasks/main.yml

---

- name: try to get the virtual environment package
  package:
    name: '{{ item }}'
  register: package_result
  ignore_errors: true
  loop:
    - python3-virtualenv
    - python-virtualenv  # for Archlinux

- name: generate the Python Virtual Environment for all users
  pip:
    virtualenv: '{{ venv_path }}'
    virtualenv_site_packages: true
    name:
      pip  # Need at least one name: or a requirements: argument and file
  register: pip_result
  ignore_errors: true
  when: not package_result.results[0].failed or not package_result.results[1].failed

- name: venv success, MANUAL ACTION ITEM
  debug:
    msg:
      - 'A Python Virtual Environment was installed in: {{ venv_path }}'
      - 'Remember to change the shebang of any personal Python programs that'
      - 'import the MythTV module to: #!{{ venv_path }}/bin/python'
  when:
    - not pip_result.failed or (pip_result.rc is defined and pip_result.rc == 0)
    - not package_result.results[0].failed or not package_result.results[1].failed

- name: venv error case, MANUAL ACTION ITEM
  debug:
    msg:
      - 'This role was unable to create a Python Virtual Environment. Either this'
      - 'playbook needs updating or manual venv installation is required. Do that'
      - 'with: python -m venv {{ venv_path }}'
  when:
    - pip_result.failed or (pip_result.rc is defined and pip_result.rc > 0)
    - package_result.results[0].failed or package_result.results[1].failed

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
