# Included by: roles/python/tasks/main.yml

---

- name: generate the Python Virtual Environment for all users
  pip:
    virtualenv: '{{ venv_path }}'
    virtualenv_site_packages: true
    name:
      pip  # Need at least one name: or a requirements: argument and file
  register: pip_result
  ignore_errors: true

- name: venv success, MANUAL ACTION ITEM
  debug:
    msg: >-
      A Python Virtual Environment was installed. Remember to change
      the shebang of any personal Python programs that import the
      MythTV module to: #!{{ venv_path }}/bin/python once cmake is
      run with: VIRTUAL_ENV={{ venv_path }} cmake --build ...
  when:
    - not pip_result.failed or (pip_result.rc is defined and pip_result.rc == 0)

- name: venv error case, MANUAL ACTION ITEM
  debug:
    msg: >-
      This role was unable to create a Python Virtual Environment. Either this
      playbook needs updating or manual venv installation is required. Do that
      with: virtualenv --system-site-packages {{ venv_path }}
  when:
    - pip_result.failed or (pip_result.rc is defined and pip_result.rc > 0)

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
