# roles/pip/tasks/pip-macOS

# Assumes that these variables are set in the macports or
# homebrew playbooks:
#
#   database_version      - specifies the database being used
#   python_package_suffix - specifiesd the version of python to use
#   MYSQLCLIENT_LDFLAGS   - flags to find the mysqlclient dylib
#   MYSQLCLIENT_CFLAGS    - flags to find the mysqlclient includes
#

---

- name: create a list of required python packages
  set_fact:
    python_pkg_list:
      - lxml
      - mysqlclient
      - oauth
      - pip>=23.0.1
      - pycurl
      - requests
      - 'requests-cache'
      - setuptools
      - urllib3
      - wheel

- name: add optional python packages
  set_fact:
    python_pkg_list:
      - '{{ python_pkg_list }}'
      - argparse
      - audiofile
      - bs4
      - common
      - configparser
      - cryptography
      - datetime
      - discid
      - et
      - features
      - HTMLParser
      - httplib2
      - importlib_metadata
      - markupsafe
      - musicbrainzngs
      - oauthlib
      - python_dateutil
      - simplejson
      - traceback2

- name: print final list of python packages
  debug:
    msg:
      '{{ lookup("flattened", python_pkg_list) }}'

- name: specify python exectuables
  set_fact:
    py_exe: '{{ pkgmgr_prefix }}/bin/python{{ python_exe_suffix }}'

- name: specify a location to install the python virtual environment
  set_fact:
    pvenv_location: '~/.mythtv/python-venv{{ python_package_suffix }}'

- name: expand the user name in the pyvenv location variable
  set_fact:
    pvenv_location: '{{ pvenv_location | expanduser }}'

- name: clearing previous python virtual environment
  file:
    path: '{{ pvenv_location }}'
    state: absent

- name: generate the python virtual environment for standard user
  become: false
  pip:
    virtualenv: '{{ pvenv_location }}'
    virtualenv_python: '{{ py_exe }}'
    virtualenv_site_packages: false
    name:
      '{{ lookup("flattened", python_pkg_list) }}'
  environment:
    MYSQLCLIENT_LDFLAGS: "{{ MYSQLCLIENT_LDFLAGS }}"
    MYSQLCLIENT_CFLAGS: "{{ MYSQLCLIENT_CFLAGS }}"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
