#!/usr/bin/bash
# ^^^^^^^^^^^^^ For shellcheck.

alias ki='docker images'
alias kps='docker ps --all'
alias kprune='docker container prune --force; docker image prune --all --force; docker image rm 2>/dev/null'

function kbuild() {
    if [ ! -f "Docker/${1}.Dockerfile" ]; then
        echo "Missing kernel:version. Probably need to: cd .., aborting"
        return 1
    fi
    docker build --tag "${1}" --file "Docker/${1}.Dockerfile" .
}

function krun () {
    if [ ! -f "Docker/${1}.Dockerfile" ]; then
        echo "Missing kernel:version. Probably need to: cd .., aborting"
        return 1
     fi
    NAME="$(echo "${1}" | tr --delete '.:' )"
    if [ -z "${NAME}" ]; then
        echo "Couldn't a name for ${1}. Try kps. aborting"
        return 1
    fi
    docker run --interactive --tty --name "${NAME}" "${1}"
}

alias  alpl='kbuild alpine:latest'
alias  amaz='kbuild amazonlinux:latest '
alias amont='kbuild amontalban:freebsd '
alias  arch='kbuild archlinux:latest'
alias cent7='kbuild centos:7'
alias cent8='kbuild centos:8'
alias cent9='kbuild centos:9'
alias cent8='kbuild centos:centos8'
alias deb10='kbuild debian:10'
alias deb11='kbuild debian:11'
alias deb12='kbuild debian:12'
alias fed40='kbuild fedora:40'
alias fed41='kbuild fedora:41'
alias  fedr='kbuild fedora:rawhide'
alias  omd4='kbuild openmandriva:4.2'
alias osusl='kbuild opensuse:leap'
alias osust='kbuild opensuse:tumbleweed'
alias rock8='kbuild rockylinux:8'
alias rock9='kbuild rockylinux:9'
alias  ub20='kbuild ubuntu:20.04'
alias  ub22='kbuild ubuntu:22.04'
alias  ub24='kbuild ubuntu:24.04'

alias ralpl='krun alpine:latest'
alias ramaz='krun amazonlinux:latest '
alias ramont='krun amontalban:freebsd '
alias rarch='krun archlinux:latest'
alias rcent8='krun centos:8'
alias rcent7='krun centos:7'
alias rcent9='krun centos:9'
alias rcent8='krun centos:centos8'
alias rdeb10='krun debian:10'
alias rdeb11='krun debian:11'
alias rdeb12='krun debian:12'
alias rfed40='krun fedora:40'
alias rfed41='krun fedora:41'
alias rfedr='krun fedora:rawhide'
alias romd4='krun openmandriva:4.2'
alias rosusl='krun opensuse:leap'
alias rosust='krun opensuse:tumbleweed'
alias rrock8='krun rockylinux:8'
alias rrock9='krun rockylinux:9'
alias rub20='krun ubuntu:20.04'
alias rub22='krun ubuntu:22.04'
alias rub24='krun ubuntu:24.04'
alias rub24='krun ubuntu:24.04'
