#!/usr/bin/bash
# ^^^^^^^^^^^^^ For shellcheck.

alias ks='echo;docker images;echo;docker ps --all'

function kprune () {
    sudo du -hs /var/lib/docker/overlay2
    echo
    docker container prune --force
    echo
    docker image prune --all --force
    echo
    # docker image remove 2>/dev/null
    sudo du -hs /var/lib/docker/overlay2
}

# 2/18/2025, docker no longer works with --file Docker/name.Dockerfile
function kbuild() {
    IMAGE="Docker/${1}.Dockerfile"

    if [ ! -f "${IMAGE}" ]; then
        echo "Missing kernel:version. check Docker/${1}, aborting"
        return 1
    fi
    cp --preserve "${IMAGE}" Dockerfile
    docker build --build-arg MY_USER_AND_GROUP="${USER}",NOBUILD="${2}" --tag "${1}" .
}

function kattach () {
#    if [ ! -f "Docker/${1}.Dockerfile" ]; then
#        echo "Missing kernel:version, aborting"
#        return 1
#     fi
    TAG="$(echo "${1}" | tr --delete '.:/')"
    if [ -z "${TAG}" ]; then
        echo "Couldn't create the tag for ${1}. Try kps. aborting"
        return 1
    fi
    docker rm "${TAG}" 2> /dev/null
    docker run --detach --hostname "${TAG}" --interactive --tty --name "${TAG}" "${1}" && docker attach "${TAG}"
}

alias  alpl='kbuild alpine:latest 1'
alias  amaz='kbuild amazonlinux:latest 1'
alias amont='kbuild amontalban:freebsd 1'
alias archl='kbuild archlinux:latest 1'
alias cent8='kbuild centos:8 1'
alias cent9='kbuild centos:9 1'
alias deb10='kbuild debian:10 1'
alias deb11='kbuild debian:11 1'
alias deb12='kbuild debian:12 1'
alias deb13='kbuild debian:13 1'
alias lmde6='kbuild lmde6-amd64:latest 1'
alias  lm22='kbuild linuxmintdmint22-amd64:latest 1'
alias fed40='kbuild fedora:40 1'
alias fed41='kbuild fedora:41 1'
alias  fedr='kbuild fedora:rawhide 1'
alias  omd4='kbuild openmandriva:4.2 1'
alias osusl='kbuild opensuse:leap 1'
alias osust='kbuild opensuse:tumbleweed 1'
alias rock8='kbuild rockylinux:8 1'
alias rock9='kbuild rockylinux:9 1'
alias  ub20='kbuild ubuntu:20.04 1'
alias  ub22='kbuild ubuntu:22.04 1'
alias  ub24='kbuild ubuntu:24.04 1'
alias  ub25='kbuild ubuntu:25.04 1'
alias ubdev='kbuild ubuntu:devel 1'

alias  ralpl='kattach alpine:latest'
alias  ramaz='kattach amazonlinux:latest'
alias ramont='kattach amontalban:freebsd'
alias rarchl='kattach archlinux:latest'
alias rcent8='kattach centos:8'
alias rcent9='kattach centos:9'
alias rdeb10='kattach debian:10'
alias rdeb11='kattach debian:11'
alias rdeb12='kattach debian:12'
alias rdeb13='kattach debian:13'
alias rlmde6='kattach lmde6-amd64:latest'
alias  rlm22='kattach linuxmintdmint22-amd64:latest'
alias rfed40='kattach fedora:40'
alias rfed41='kattach fedora:41'
alias  rfedr='kattach fedora:rawhide'
alias  romd4='kattach openmandriva:4.2'
alias rosusl='kattach opensuse:leap'
alias rosust='kattach opensuse:tumbleweed'
alias rrock8='kattach rockylinux:8'
alias rrock9='kattach rockylinux:9'
alias  rub20='kattach ubuntu:20.04'
alias  rub22='kattach ubuntu:22.04'
alias  rub24='kattach ubuntu:24.04'
alias  rub25='kattach ubuntu:25.04'
alias rubdev='kattach ubuntu:devel'
