# roles/mythtv-deb/tasks/debian_ubuntu.yml

---

- name: add compilers and build essentials 2 (debian)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libtool-bin
  when: ansible_distribution == "Debian" and ansible_lsb.major_release|int >= 8

- name: add compilers and build essentials 2 (ubuntu)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libtool-bin
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int >= 15

- name: add mythtv extra build libraries (Raspbian Stretch or later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libxcb-shm0-dev
      - libx265-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int >= 9
    - ansible_lsb.id == "Raspbian"

- name: add mythtv extra build libraries (Raspbian Stretch)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec4-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int == 9
    - ansible_lsb.id == "Raspbian"

- name: add mythtv extra build libraries (Raspbian Buster or later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec-dev
      - hwdata
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int >= 10
    - ansible_lsb.id == "Raspbian"

- name: add mythtv extra build libraries (Debian)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec-dev
      - libcrystalhd-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.id != "Raspbian"
    - ansible_distribution_release != "bookworm"
    - ansible_distribution_major_version|int < 11

- name: add mythtv extra build libraries (Debian Bullseye and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "Bullseye" or ansible_distribution_major_version|int >= 11

- name: add mythtv extra build libraries (Debian Stretch and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libbluray-dev
      - libx265-dev
  when:
    - ansible_distribution == "Debian"
    - (ansible_lsb.major_release|int >= 9 or ansible_lsb.release == "testing")

- name: add mythtv extra build libraries (Ubuntu 16.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec-dev
      - libavc1394-dev
      - libiec61883-dev
      - libpulse-dev
      - libfftw3-dev
      - libssl-dev
      - libsystemd-dev
      - libbluray-dev
      - libx265-dev
  when:
    - ansible_distribution == "Ubuntu"
    - (ansible_lsb.major_release|int >= 16)

- name: add mythtv extra build libraries (Ubuntu 16.04 and later, not aarch64)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcrystalhd-dev
  when:
    - ansible_distribution == "Ubuntu"
    - (ansible_lsb.major_release|int >= 16)
    - ansible_architecture != "aarch64"

- name: add mythtv mysql client libraries (Ubuntu)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libmysqlclient-dev
  when: ansible_distribution == "Ubuntu"

- name: add mythtv mysql client libraries (Debian - Jessie)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libmysqlclient-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int == 8

- name: add mythtv mysql client libraries (Debian - Stretch)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - default-libmysqlclient-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int == 9

- name: add mythtv mysql client libraries (Debian - Buster)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libmariadbclient-dev
      - libmariadb-dev-compat
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int == 10

- name: add mythtv mysql client libraries (Debian - Bullseye and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - default-libmysqlclient-dev
      - libmariadb-dev-compat
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "Bullseye" or ansible_distribution_major_version|int >= 11

- name: add mythtv essential python modules
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-mysqldb
      - python-lxml
      - python-urlgrabber
      - python-oauth
      - python-pycurl
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_lsb.major_release|int < 20

- name: add mythtv essential python modules (Stretch/16.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-future
      - python3-future
      - python-requests
      - python-requests-cache
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python-simplejson
      - python3-simplejson
  when: (ansible_distribution == "Debian" and
          (ansible_lsb.major_release|int >= 9 and ansible_distribution_major_version|int < 11) or
        (ansible_distribution == "Ubuntu" and
          (ansible_lsb.major_release|int >= 16 and ansible_lsb.major_release|int < 20)))

- name: add mythtv essential python modules (Ubuntu 20.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python3-future
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python3-pycurl
      - python3-simplejson
      - python3-setuptools
  when:
    - (ansible_distribution == "Ubuntu")
    - (ansible_lsb.major_release|int >= 20 )

- name: add mythtv essential python modules (Buster)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-future
      - python3-future
      - python3-oauth
      - python3-pycurl
      - python-requests
      - python3-requests-cache
  when:
    - ansible_distribution == "Debian"
    - ansible_lsb.major_release|int == 10

- name: add mythtv essential python modules (Buster or later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python3-future
      - python3-oauth
      - python3-pycurl
      - python3-requests
      - python3-requests-cache
      - python3-lxml
      - python3-mysqldb
      - python3-simplejson
      - python3-setuptools
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "Bullseye" or ansible_distribution_major_version|int >= 11

- name: add mythtv essential plugin libraries (Debian or Ubuntu 16+)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libminizip-dev
  when: ansible_distribution == "Debian" or
        (ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int >= 16)

- name: adjust Ubuntu 22.04 packages
  block:
    - set_fact:
        deb_pkg_lst: '{{ lookup("flattened", deb_pkg_lst ).split(",") }}'

    - set_fact:
        deb_pkg_lst: "{{ deb_pkg_lst | difference(['libcrystalhd-dev']) }}"

    - set_fact:
        deb_pkg_lst: "{{ deb_pkg_lst | replace('python3-oauth', 'python3-oauthlib') }}"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int == 22

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
