# roles/mythtv-deb/tasks/ubuntu.yml

---

- name: ubuntu | Add compilers and build essentials 2
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libtool-bin
      - sqlite3
  when: ansible_lsb.major_release|int >= 15

- name: ubuntu | Add mythtv extra build libraries (16.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec-dev
      - libavc1394-dev
      - libiec61883-dev
      - libpulse-dev
      - libbluray-dev
      - libx265-dev
      - libsqlite3-dev
  when:
    - ansible_lsb.major_release|int >= 16

- name: ubuntu | Add mythtv extra build libraries (16.04 and later, not aarch64)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcrystalhd-dev
  when:
    - ansible_lsb.major_release|int >= 16
    - ansible_architecture != "aarch64"

- name: ubuntu | Add mythtv mysql client libraries
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libmysqlclient-dev

- name: ubuntu | Add mythtv essential python modules
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-mysqldb
      - python-lxml
      - python-urlgrabber
      - python-oauth
      - python-pycurl
  when:
    - ansible_lsb.major_release|int < 20

- name: ubuntu | Add mythtv essential python modules (16.04 to 19.10)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-future
      - python3-future
      - python-requests
      - python-requests-cache
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python-simplejson
      - python3-simplejson
  when:
    - ansible_lsb.major_release|int >= 16 and ansible_lsb.major_release|int < 20

- name: ubuntu | Add mythtv essential python modules (20.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python3-future
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python3-pycurl
      - python3-setuptools
      - python3-venv
      - python3-virtualenv
      - python3-wheel
      - python3-dev
  when:
    - ansible_lsb.major_release|int >= 20 and ansible_lsb.major_release|int < 24

- name: ubuntu | Add mythtv essential python modules (24.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python3-pycurl
      - python3-setuptools
      - python3-venv
      - python3-virtualenv
      - python3-wheel
      - python3-dev
  when:
    - ansible_lsb.major_release|int >= 24

- name: ubuntu | Add python3-pip module (20.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python3-venv
      - python3-wheel
      - python3-pip
  when:
    - ansible_lsb.major_release|int >= 20

- name: ubuntu | Add mythtv essential plugin libraries (16.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libminizip-dev
  when:
    - ansible_lsb.major_release|int >= 16

- name: ubuntu | Adjust 22+ packages
  when:
    - ansible_distribution_major_version | int >= 22
  block:
    - name: ubuntu | Flatten package list
      set_fact:
        deb_pkg_lst: '{{ lookup("flattened", deb_pkg_lst).split(",") }}'

    - name: ubuntu | Treat libcrystalhd-dev
      set_fact:
        deb_pkg_lst: "{{ deb_pkg_lst | difference(['libcrystalhd-dev']) }}"

    - name: ubuntu | Convert Python oauth to oauthlib
      set_fact:
        deb_pkg_lst: "{{ deb_pkg_lst | replace('python3-oauth', 'python3-oauthlib') }}"

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
