# roles/mythtv-deb/tasks/ubuntu.yml

---

- name: add compilers and build essentials 2
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libtool-bin
  when: ansible_lsb.major_release|int >= 15

- name: add mythtv extra build libraries (16.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcec-dev
      - libavc1394-dev
      - libiec61883-dev
      - libpulse-dev
      - libbluray-dev
      - libx265-dev
  when:
    - ansible_lsb.major_release|int >= 16

- name: add mythtv extra build libraries (16.04 and later, not aarch64)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libcrystalhd-dev
  when:
    - ansible_lsb.major_release|int >= 16
    - ansible_architecture != "aarch64"

- name: add mythtv mysql client libraries
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libmysqlclient-dev

- name: add mythtv essential python modules
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-mysqldb
      - python-lxml
      - python-urlgrabber
      - python-oauth
      - python-pycurl
  when:
    - ansible_lsb.major_release|int < 20

- name: add mythtv essential python modules (16.04 to 19.10)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python-future
      - python3-future
      - python-requests
      - python-requests-cache
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python-simplejson
      - python3-simplejson
  when:
    - ansible_lsb.major_release|int >= 16 and ansible_lsb.major_release|int < 20

- name: add mythtv essential python modules (20.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - python3-future
      - python3-requests
      - python3-requests-cache
      - python3-mysqldb
      - python3-lxml
      - python3-oauth
      - python3-pycurl
      - python3-simplejson
      - python3-setuptools
  when:
    - ansible_lsb.major_release|int >= 20

- name: add mythtv essential plugin libraries (16.04 and later)
  set_fact:
    deb_pkg_lst:
      - '{{ deb_pkg_lst }}'
      - libminizip-dev
  when:
    - ansible_lsb.major_release|int >= 16

- name: adjust 22+ packages
  block:
    - set_fact:
        deb_pkg_lst: '{{ lookup("flattened", deb_pkg_lst ).split(",") }}'

    - set_fact:
        deb_pkg_lst: "{{ deb_pkg_lst | difference(['libcrystalhd-dev']) }}"

    - set_fact:
        deb_pkg_lst: "{{ deb_pkg_lst | replace('python3-oauth', 'python3-oauthlib') }}"
  when:
    - ansible_distribution_major_version | int >= 22

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
