#!/usr/bin/env ansible-playbook

---

- name: define variables used for AUR/yay work
  ansible.builtin.set_fact:
    yay_repository: 'https://aur.archlinux.org/yay.git'
    yay_build_directory: '/tmp/yay_build'
    yay_is_installed: false
    aur_packages:
      - perl-net-upnp
      - python-timeout-decorator
      - python-requests-cache
      - libhdhomerun

- name: check if the yay command exists (assumes yay can be found in $PATH)
  ansible.builtin.command: yay --version
  check_mode: false
  changed_when: false
  register: yay_response
  ignore_errors: true

- name: mark yay installed
  set_fact:
    yay_is_installed: true
  when: yay_response is defined and not yay_response.failed

- ansible.builtin.debug:
    msg: "yay wasn't in your $PATH, assuming it must be installed from AUR."
  when: not yay_is_installed

- name: download the yay repository
  become: false
  ansible.builtin.git:
    repo: '{{ yay_repository }}'
    dest: '{{ yay_build_directory }}'
  register: git_response
  ignore_errors: true
  when: not yay_is_installed

- name: start by marking the yay repo not loaded
  set_fact:
    yay_repo_loaded: false

- name: yay repo downloaded from AUR OK, mark repo loaded
  set_fact:
    yay_repo_loaded: true
  when:
    - git_response is defined
    - git_response.skipped is undefined
    - not git_response.failed

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg:
      - 'You can run: makepkg -siD {{ yay_build_directory }} to build yay. Then'
      - 'manually run the following command to add AUR packages:'
  when: yay_repo_loaded

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg:
      - "Because no download from: {{ yay_repository }} was done, you'll"
      - "need to get yay yourself, Then run:"
  when:
    - not yay_repo_loaded
    - not yay_is_installed

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg: 'Run the following command to add AUR packages:'
  when: yay_is_installed

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg: 'yay -S {{ lookup("flattened", aur_packages) | regex_replace(",", " ") }}'
    # msg: 'yay -S {{ list_o_strings | flatten() | regex_replace(",", " ") }}'

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2,80:
