#!/usr/bin/env ansible-playbook

# Experimental: to run these tasks, change the 'normal' command to:
#
#   ./mythtv.yml --extra-vars='{"yay_flag":true}' --limit=localhost
#

---

- name: define variables used for AUR/yay work
  ansible.builtin.set_fact:
    yay_repository: 'https://aur.archlinux.org/yay.git'
    yay_build_directory: '/tmp/yay_build'
    yay_is_installed: false
    aur_package_list:
      - libhdhomerun
      - perl-net-upnp
      - python-timeout-decorator
      - python-requests-cache

- name: check if the yay command exists (assumes yay can be found in $PATH)
  ansible.builtin.command: yay --version
  check_mode: false
  changed_when: false
  register: yay_response
  ignore_errors: true

- set_fact:
    yay_is_installed: true
  when: yay_response is defined and not yay_response.failed

- ansible.builtin.debug:
    msg: "yay wasn't in your $PATH, assuming it must be installed from AUR."
  when: not yay_is_installed

- name: download the yay repository
  become: false
  ansible.builtin.git:
    repo: '{{ yay_repository }}'
    dest: '{{ yay_build_directory }}'
  register: git_response
  ignore_errors: true
  when: not yay_is_installed

- set_fact:
    yay_repo_loaded: false

- set_fact:
    yay_repo_loaded: true
  when:
    - git_response is defined
    - git_response.skipped is undefined
    - not git_response.failed

# This can't work because makepkg must not run as root AND it prompts for the
# sudo password after starting. The ansible.builtin.expect module was tested
# but doesn't seem to work. It is possible to change PACMAN_AUTH=(/usr/bin/true
# but that seems unsafe.)
- name: make the yay package
  become: false
  ansible.builtin.command: makepkg -si
  args:
    chdir: ./yay
  tags: never

# This is also turned off because pacman calls makepkg. See the task above for
# reasons.
- name: add the AUR packages NOT CLEAR IF extra_args MUST BE INCLUDED
  become: false
  community.general.pacman:
    name: '{{ item }}'
    state: present
    executable: yay
    extra_args: '--builddir {{ yay_build_directory }}'
  loop:
    - libhdhomerun
    - perl-net-upnp
    - python-timeout-decorator
    - python-requests-cache
  tags: never

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg:
      - 'You can run: makepkg -siD {{ yay_build_directory }} to build yay.'
      - 'Then manually run the following commands to add AUR packages:'
  when: yay_repo_loaded

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg:
      - "Because no download from: {{ yay_repository }} was done, you'll"
      - "need to install yay manually, THEN run:"
  when:
    - not yay_repo_loaded
    - not yay_is_installed

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg: 'Run the following commands to add AUR packages:'
  when: yay_is_installed

- name: MANUAL ACTION ITEM
  ansible.builtin.debug:
    msg: 'yay -S {{ lookup("flattened", aur_package_list) }}'

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2,80:
