# roles/mythtv-macports/tasks/main.yml

---

- name: create a list of compilers and build essentials
  set_fact:
    macports_pkg_list:
      - ccache
      - nasm
      - autoconf
      - automake
      - pkgconfig

- name: add essential libraries
  set_fact:
    macports_pkg_list:
      - '{{ macports_pkg_list }}'
      - libxml2
      - taglib
      - exiv2
      - libbluray
      - lzo2
      - libsamplerate
      - libcec

- name: add optional libraries
  set_fact:
    macports_pkg_list:
      - '{{ macports_pkg_list }}'
      - openssl
      - libvpx
      - x264
      - x265
      - XviD
      - libvorbis
      - flac
      - faac
      - freetype
      - libxml2
      - fftw-3
      - libass
      - x264
      - x265
      - libvpx
      - minizip
      - apache-ant
      - hdhomerun
      - libX11
      - liberation-fonts
      - dejavu-fonts

- name: develop a Python package version suffix
  set_fact:
    python_package_suffix:
      '{{ ansible_python.version.major }}{{ ansible_python.version.minor }}'

- name: add python essentials
  set_fact:
    macports_pkg_list:
      - '{{ macports_pkg_list }}'
      - python{{ python_package_suffix }}
      - py{{ python_package_suffix }}-future
      - py{{ python_package_suffix }}-requests
      - py{{ python_package_suffix }}-requests-cache
      - py{{ python_package_suffix }}-lxml
      - py{{ python_package_suffix }}-oauthlib
      - py{{ python_package_suffix }}-curl
      - py{{ python_package_suffix }}-simplejson
      - py{{ python_package_suffix }}-wheel
      - py{{ python_package_suffix }}-pip
      - py{{ python_package_suffix }}-pymysql

- name: add perl essentials
  set_fact:
    macports_pkg_list:
      - '{{ macports_pkg_list }}'
      - perl5
      - p5-date-manip
      - p5-datetime-format-iso8601
      - p5-dbi
      - p5-dbd-mysql
      - p5-image-size
      - p5-io-socket-inet6
      - p5-json
      - p5-libwww-perl
      - p5-http-request-ascgi
      - p5-net-upnp
      - p5-soap-lite
      - p5-xml-xpath
      - p5-xml-simple

- name: packages from ports
  set_fact:
    macports_pkg_list:
      - '{{ macports_pkg_list }}'
      - gmake
      - libtool
      - lame
      - gnutls

- name: print final list of ports
  debug:
    msg:
      '{{ lookup("flattened", macports_pkg_list) }}'

- name: install packages
  become: yes
  become_user: root
  become_method: sudo
  macports:
    name:
      '{{ lookup("flattened", macports_pkg_list) }}'
    update_cache: yes

- name: select the installed version of python and pip
  become: yes
  become_user: root
  become_method: sudo
  command: 'port select --set {{ item.group }} {{ item.version }}'
  loop:
    - { group: python,  version: 'python{{ python_package_suffix }}' }
    - { group: python3, version: 'python{{ python_package_suffix }}' }
    - { group: pip,     version: 'pip{{ python_package_suffix }}' }
    - { group: pip3,    version: 'pip{{ python_package_suffix }}' }

- name: install mysqlclient (for mysqldb)
  pip:
      name: mysqlclient
      executable: pip3
  tags: pip

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
