- include:  qt4-deb.yml
  when:     ansible_pkg_mgr == "apt"

- include:  qt4-rpm.yml
  when:     ansible_pkg_mgr == "yum"

- include:  qt4-dnf.yml
  when:     ansible_pkg_mgr == "dnf"

- include:  qt4-pacman.yml
  when:     ansible_pkg_mgr == "pacman"

- include:  qt4-pkgng.yml
  when:     ansible_pkg_mgr == "pkgng"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
