---
DOCUMENTATION:
  name: git_log_info
  author: Bill Meek
  short_description: Get some git info about the playbook or a single file
  description:
    - See OPTIONS for the details of the returned data. The filter also
    - checks that git exists in the PATH of the user running the playbook
    - and returns explanations if it isn't. N/A is returned if git can't
    - find anything, e.g when the file isn\'t under git control.
  options:
    scope:
      description: picks the format of information returned
      type: string
      default: playbook
      choices: playbook, full, long
      choices_: |

        - playbook: gets the SHA1 of HEAD
        - full: gets the short SHA1, author and timestamp of a file
        - long: gets the entire SHA1 of a file
      required: false

EXAMPLES: |
  - name: get a file's SHA1 (short), author and timestamp
    ansible.builtin.debug:
      var: '{{ some_file_name | git_log_info("full") }}'

  - name: 'get long SHA1, author and timestamp for the project'
    ansible.builtin.debug:
      var: '{{ any_file_name | git_log_info("project") }}'

RETURN:
  _:
    description: the git information requested
    type: string
    returned: always
    sample: "2cbfd35 by Some Author on Mon, 1 Dec 2025 14:01:57 -0600"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=80:
