---
DOCUMENTATION:
  name: git_log_info
  author: Bill Meek
  short_description: Get some git info about the playbook or a single file
  description:
    - Return some git log information.
    - ''
    - See OPTIONS for the details of the returned data. The filter also
    - checks that git exists in the PATH of the user running the playbook
    - and returns explanations if it can't be found. N/A is returned if
    - git can't find anything, e.g when the file isn't under git control.
  plugin_type: filter
  options:
    _input:
      description: a file name (or HEAD) to get information about
      type: string
      default: playbook
      choices: a file name or HEAD
      required: true
    scope:
      description: picks the format of information returned
      type: string
      default: playbook
      choices: playbook, full, long (for HEAD, file+detail or file's SHA1)
      required: false

EXAMPLES: |
  - name: "get a file's short SHA1, author and timestamp"
    ansible.builtin.debug:
      var: "{{ some_file_name | git_log_info('full') }}"

  - name: "get the long SHA1 for the MythTV playbook (HEAD)"
    ansible.builtin.debug:
      var: "{{ 'HEAD' | git_log_info('playbook') }}"

RETURN:
  _output:
    description: the requested information
    type: string
    returned: always
    sample: "a1b2c3d by Some Author on Mon, 1 Jan 1900 10:10:10 -1000"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=80:
