---

packages:
  - git
  - gcc
  - gcc-c++
  - make
  - gdb
  - automake
  - autoconf
  - libtool
  - pkgconfig
  - which
  - diffutils
  - cmake
  - patch
  - ninja-build
  - gperf
  - meson
  - nasm
  - ccache
  - sqlite
  - php
  - gawk
  - libuuid-devel
  - libxml2-devel
  - alsa-lib-devel
  - pulseaudio-libs-devel
  - avahi-compat-libdns_sd-devel
  - exiv2-devel
  - lzo-devel
  - hdhomerun-devel
  - libsamplerate-devel
  - libzip-devel
  - libmpeg2-devel
  - expat-devel
  - soundtouch-devel
  - lame-devel
  - libv4l-devel
  - libXNVCtrl-devel
  - libXinerama-devel
  - libXrandr-devel
  - libXv-devel
  - libva-devel
  - libdrm-devel
  - libvdpau-devel
  - libass-devel
  - libiec61883-devel
  - fftw-devel
  - systemd-devel
  - xvidcore-devel
  - x264-devel
  - x265-devel
  - libvpx-devel
  - gnutls-devel
  - libdav1d-devel
  - libcec-devel
  - libcrystalhd-devel
  - libavc1394-devel
  - libbluray-devel
  - libbluray-bdj
  - python3-lxml
  - python3-libselinux
  - python3-requests-cache
  - python3-simplejson
  - python3-setuptools
  - python3-devel
  - python3-mysql
  - python3-wheel
  - python3-pip
  - python3-virtualenv
  - perl-ExtUtils-MakeMaker
  - perl-DBI
  - perl-DBD-MySQL
  - perl-HTTP-Message
  - perl-libwww-perl
  - perl-IO-Socket-INET6
  - perl-Date-Manip
  - perl-XML-Simple
  - perl-XML-XPath
  - perl-DateTime-Format-ISO8601
  - perl-SOAP-Lite
  - perl-JSON
  - perl-Image-Size
  - perl-Net-UPnP
  - perl(Sys::Hostname)
  - perl(FindBin)
  - perl(IPC::Cmd)
  - libvorbis-devel
  - flac-devel
  - taglib-devel
  - libcdio-devel
  - libcdio-paranoia-devel
  - mysql-devel
  - minizip-devel
  - python3-oauth
  - python3-pycurl
  - python3-oauthlib
  - qt5-qtbase-devel
  - qt5-qtwebkit-devel
  - qt5-qtscript-devel
  - qt5-qtbase-mysql

...
