# 2025/02/20 1st try at universal tasks that <<should>> work for any
# distribution. Runs after the 'normal' packages have been installed.
# Python and pip should be there. NB Early testing shows that Debian
# hosts must: apt install python3.12-venv. But python3-venv works at
# least in v25.04, Debian 11,

---

- name: create a python virtual environment
  ansible.builtin.command:
    argv:
      - '{{ ansible_python.executable }}'
      - '-m'
      - 'venv'
      - '{{ venv_path }}'
  register: venv_result
  ignore_errors: true

- name: add essential python modules to the virtual environment
  ansible.builtin.pip:
    name: '{{ item }}'
    virtualenv: '{{ venv_path }}'
  loop:
    - lxml
    - mysqlclient
    - requests
    - pip    # This was probably done already by creating the venv
    - setuptools  # As above
    - wheel  # This was probably included by the pip module
  register: pip_result
  ignore_errors: true
  when: venv_result.rc == 0

- name: venv success, print the venv path used
  ansible.builtin.debug:
    msg:
      - 'A Python virtual environment was installed in: {{ venv_path }}.'
  when: venv_result.rc == 0

- name: venv error case, explain what happened
  ansible.builtin.debug:
    msg:
      - 'pip was unable to create a Python Virtual Environment. Either this'
      - 'playbook needs updating or manual venv installation is required.'
      - '{{ venv_path }} is the path this task used.'
  when: venv_result.rc > 0

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
