# 2025/02/20 1st try at universal tasks that <<should>> work for any
# distribution. Runs after the 'normal' packages have been installed.
# Python and pip should be there. NB Early testing shows that Debian
# hosts must: apt install python3.12-venv. But python3-venv works at
# least in v25.04, Debian 11,

# Debian 10's python is 2.7, so we can't use ansible_python.executable.
# It also doesn't recognize FQCNs or fully qualified collection names.
---

- name: create a python virtual environment
  command:
    argv:
      - python3
      - '-m'
      - 'venv'
      - '{{ venv_path }}'
  register: venv_result
  ignore_errors: true

- name: add essential python modules to the virtual environment
  pip:
    name: '{{ item }}'
    virtualenv: '{{ venv_path }}'
  loop:
    - lxml
    - mysqlclient # Requires Python.h
    - requests
    - pip         # This gets done by creating the venv
    - setuptools
    - wheel
  register: pip_result
  ignore_errors: true
  when: venv_result.rc == 0

- name: venv success, print the venv path used
  debug:
    msg:
      - 'A Python Virtual Environment was installed in: {{ venv_path }}.'
  when: venv_result.rc == 0

- name: venv error case, explain what happened
  debug:
    msg:
      - 'pip was unable to create a Python Virtual Environment. Either this'
      - 'playbook needs updating or manual venv installation is required.'
      - '{{ venv_path }} is the path this task used.'
  when: venv_result.rc > 0

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
