---

# parse out database name and major/minor version
# database_version is set in the macports main.yml
- name: qt5-macports | Specify mysql/mariadb database version to compile against
  set_fact:
    qt_mysql_variant: "{{ database_version | regex_replace('-') | regex_replace('\\.', '_') }}"

- name: qt5-macports | Create list of qt5 libraries
  set_fact:
    macports_pkg_list:
      - qt5
      - qt5-qtscript
      - qt5-qtwebengine
  tags:
    - qt5

- name: qt5-macports | Print final qt5 list of ports
  debug:
    msg:
      '{{ lookup("flattened", macports_pkg_list) }}'

- name: qt5-macports | Install port qt5 packages
  macports:
    name:
      '{{ lookup("flattened", macports_pkg_list) }}'
    update_cache: true
  tags:
    - qt5

- name: qt5-macports | Install qt5-mysql-plugin for previously specified mariadb/mysql version
  macports:
    name: qt5-mysql-plugin
    variant: +{{ qt_mysql_variant }}
  tags:
    - qt5

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
