- name: create list of qt5 libraries
  set_fact:
    macports_pkg_list:
      - qt5
      - qt5-qtwebkit
      - qt5-qtscript
      - qt5-mysql-plugin
  tags:
    - qt5

- name: print final qt5 list of ports
  debug:
    msg:
      '{{ lookup("flattened", macports_pkg_list) }}'

- name: install port qt5 packages
  become: yes
  become_user: root
  become_method: sudo
  macports:
    name:
      '{{ lookup("flattened", macports_pkg_list) }}'
    update_cache: yes
  tags:
    - qt5

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
