---

- name: qt5-suse | Create a list of qt5 libraries
  set_fact:
    zypper_pkg_lst:
      - libqt5-qtbase-devel
      - libqt5-qtscript-devel
  tags:
    - qt5

- name: qt5-suse | Create a list of qt5 WebKit libraries
  set_fact:
    zypper_pkg_lst:
      - '{{ zypper_pkg_lst }}'
      - libQt5WebKit5-devel
      - libQt5WebKitWidgets-devel
  when: ansible_distribution == "openSUSE Leap"
  tags:
    - qt5

# This looks like overkill, but the intent is to provide future maintainers
# with a template to add more (especially conditional) packages.

- name: qt5-suse | Add qt5 runtime dependencies
  set_fact:
    zypper_pkg_lst:
      - '{{ zypper_pkg_lst }}'
      - libQt5Sql5-mysql
  tags:
    - qt5

- name: qt5-suse | Final zypper qt5 package list
  debug:
    msg:
      '{{ lookup("flattened", zypper_pkg_lst) }}'
  tags:
    - qt5

- name: qt5-suse | Install zypper qt5 packages
  zypper:
    name:
      '{{ lookup("flattened", zypper_pkg_lst) }}'
    state:
      present
  tags:
    - qt5

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
