# roles/mythtv-rpm/tasks/setup-rpmfusion.yml

---

- shell:            /bin/rpm -q --quiet rpmfusion-free-release && echo installed || echo missing
  register:         rpmfusion

- shell:            /usr/bin/grep -qi Rawhide /etc/fedora-release && echo rawhide || echo release
  register:         rawhide

- name: setup RPMFusion repository (Fedora rawhide)
  command:
    cmd: dnf install -y --nogpgcheck {{ rpmfusion_rawhide_rpm }}
  when:
    - ansible_distribution == "Fedora"
    - rpmfusion.stdout == "missing"
    - rawhide.stdout == "rawhide"

- name: setup RPMFusion repository (Fedora release versions)
  command:
    cmd: dnf install -y --nogpgcheck {{ rpmfusion_rpm }}
  when:
    - ansible_distribution == "Fedora"
    - rpmfusion.stdout == "missing"
    - rawhide.stdout == "release"

- name: setup RPMFusion repository (CentOS release versions)
  command:
    cmd: dnf install -y --nogpgcheck {{ rpmfusion_el_rpm }}
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Rocky"
    - rpmfusion.stdout == "missing"
