# roles/mythtv-rpm/tasks/setup-rpmfusion.yml

---

- shell:            /bin/rpm -q --quiet rpmfusion-free-release && echo installed || echo missing  # noqa command-instead-of-module
  register:         rpmfusion

- shell:            /usr/bin/grep -qi Rawhide /etc/fedora-release && echo rawhide || echo release
  register:         rawhide

- name: setup-rpmfusion | Enable the RPM Fusion repository
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
    state: present
  when: ansible_distribution == 'Fedora'

- name: setup-rpmfusion | Setup RPMFusion repository (Fedora release versions)
  command:
    cmd: dnf install -y --nogpgcheck {{ rpmfusion_rpm }}
  when:
    - ansible_distribution == "Fedora"
    - rpmfusion.stdout == "missing"
    - rawhide.stdout == "release"

- name: setup-rpmfusion | Setup RPMFusion repository (CentOS release versions)
  command:
    cmd: dnf install -y --nogpgcheck {{ rpmfusion_el_rpm }}
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Rocky"
    - rpmfusion.stdout == "missing"
