# These tasks will run before any host (mostly for those in hosts.yml) and
# prevent users from running ALL hosts. The instructions are clear that
# the --limit=<name> must be used.

---

- debug:
    msg: "inventory_hostname='{{ inventory_hostname }}'"
    verbosity: 1

- fail:
    msg: "Aborting {{ ansible_hostname }} because the --limit switch wasn't used"
  when: ansible_limit is not defined

- fail:
    msg: "Aborting {{ ansible_hostname }} because the --limit=all switch was used"
  when: ansible_limit == "all"

- assert:
    that: ansible_limit
    success_msg: "--limit={{ ansible_limit }}, GOOD!"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
