# These tasks will run before other roles (selected by mythtv.yml) and
# prevent users from running ALL hosts. The instructions are clear that
# the --limit=<name> must be used. The debug: prints information useful
# for diagnosing issues.
#
# Next, print some valuable debugging information
#
# Finally, load any user specific variables (not under git control).

---

- name: "Don't do limit checks if using rhosts.yml"
  when:  inventory_file is not search("/rhosts.yml$")
  block:
    - fail:
        msg: "Aborting play because the --limit switch wasn't used"
      when: ansible_limit is undefined
    - fail:
        msg: "Aborting play because the --limit= switch was empty"
      when: not ansible_limit
    - fail:
        msg: "Aborting play because --limit=all was used"
      when: ansible_limit == "all"

- name: "{{ instruction_text }}:"
  debug:
    msg:
      - "inventory_hostname:                 {{ inventory_hostname }}"
      - "ansible_distribution:               {{ ansible_distribution }}"
      - "ansible_distribution_release:       {{ ansible_distribution_release }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_lsb.major_release:          {{ ansible_lsb.major_release }}"
      - "ansible_pkg_mgr:                    {{ ansible_pkg_mgr }}"
      - "ansible_version.full:               {{ ansible_version.full }}"
      - "ansible_distribution_version:       {{ ansible_distribution_version }}"
  when:
    - ansible_lsb.major_release is defined

- name: "{{ instruction_text }}:"
  debug:
    msg:
      - "inventory_hostname:                 {{ inventory_hostname }}"
      - "ansible_distribution:               {{ ansible_distribution }}"
      - "ansible_distribution_release:       {{ ansible_distribution_release }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_pkg_mgr:                    {{ ansible_pkg_mgr }}"
      - "ansible_version.full:               {{ ansible_version.full }}"
  when: ansible_lsb.major_release is undefined

- name: Load user_options.yml
  include_vars:
    file: '{{ item }}'
  with_first_found:
    - files: group_vars/user_options.yml
      skip: true

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2,80:
