# These tasks will run before other roles (selected by mythtv.yml) and
# prevent users from running ALL hosts. The instructions are clear that
# the --limit=<name> must be used. The debug: prints information useful
# for diagnosing issues.
#
# Finally, load any user specific variables (not under git control).

---

- name: Do limit checks when using hosts.yml
  when:
    inventory_file is search("/hosts.yml$") and (
    ansible_limit is undefined or
    ansible_limit | length == 0 or
    ansible_limit == "all")
  block:
    - name: "Limit switch must be used, e.g. ./mythtv-yml --limit=localhost"
      debug:
        msg: "Aborting because the --limit switch was missing, empty or set to 'all'"
    - meta: end_play

- name: Gather facts
  setup:

- name: '{{ instruction_text }}:'
  debug:
    msg:
      - 'inventory_hostname:                        {{ inventory_hostname }}'
      - 'ansible_facts[distribution]:               {{ ansible_facts["distribution"] }}'
      - 'ansible_facts[distribution_release]:       {{ ansible_facts["distribution_release"] }}'
      - 'ansible_facts[distribution_major_version:  {{ ansible_facts["distribution_major_version"] }}'
      - 'ansible_facts[lsb.major_release]:          {{ ansible_facts["lsb.major_release"] }}'
      - 'ansible_facts[pkg_mgr]:                    {{ ansible_facts["pkg_mgr"] }}'
      - 'ansible_version.full:                      {{ ansible_version.full }}'
      - 'ansible_facts[distribution_version]:       {{ ansible_facts["distribution_version"] }}'
  when:
    - ansible_facts["lsb.major_release"] is defined

- name: '{{ instruction_text }}:'
  debug:
    msg:
      - 'inventory_hostname:                        {{ inventory_hostname }}'
      - 'ansible_facts[distribution]:               {{ ansible_facts["distribution"] }}'
      - 'ansible_facts[distribution_release]:       {{ ansible_facts["distribution_release"] }}'
      - 'ansible_facts[distribution_major_version:  {{ ansible_facts["distribution_major_version"] }}'
      - 'ansible_facts[pkg_mgr]:                    {{ ansible_facts["pkg_mgr"] }}'
      - 'ansible_version.full:                      {{ ansible_version.full }}'
  when: ansible_facts["lsb.major_release"] is undefined

- name: Load user_options.yml
  include_vars:
    file: '{{ item }}'
  with_first_found:
    - files: group_vars/user_options.yml
      skip: true

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2,80:
