# roles/mythtv-homebrew/tasks/main.yml

---
- name: Get homebrew install prefix
  command: brew --prefix
  register: HB_OUT

- name: set pkgmgr_prefix fact
  set_fact: pkgmgr_prefix={{ HB_OUT.stdout  }}

- name: specify a mariadb/mysql version to install
  set_fact: database_version=mariadb
  when: database_version is undefined

- name: check if this is a mariadb based install
  set_fact: database_name=mariadb
  when: database_version is search("mariadb")

- name: check if this is a mysql based install
  set_fact: database_name=mysql
  when: database_version is search("mysql")

- name: create a list of compilers and build essentials
  set_fact:
    homebrew_pkg_list:
      - ccache
      - nasm
      - autoconf
      - automake
      - 'pkg-config'
      - cmake
      - gpatch
      - ninja
      - gperf
      - meson

# note that on homebrew, mysql-client
# is required to get the python mysqlclient working
- name: add essential libraries
  set_fact:
    homebrew_pkg_list:
      - '{{ homebrew_pkg_list }}'
      - libxml2
      - libxslt
      - taglib
      - exiv2
      - libbluray
      - lzo
      - libsamplerate
      - libzip
      - zlib
      - libiconv
      - glslang
      - openssl
      - '{{ database_version }}'
      - 'mysql-client'

- name: add optional libraries
  set_fact:
    homebrew_pkg_list:
      - '{{ homebrew_pkg_list }}'
      - libvpx
      - x264
      - x265
      - XviD
      - libvorbis
      - flac
      - faac
      - freetype
      - fftw
      - libass
      - aom
      - dav1d
      - minizip
      - ant
      - libhdhomerun
      - libX11
      - php
      - 'sound-touch'
      - libcec
      - zstd
      - 'vulkan-headers'
      - 'vulkan-tools'
      - 'vulkan-loader'
      - 'molten-vk'
      - libdiscid

- name: develop a Python package version suffix
  set_fact:
    python_package_suffix:
      '{{ ansible_python.version.major }}{{ ansible_python.version.minor }}'
    python_exe_suffix:
      '{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}'

- name: add python essentials
  set_fact:
    homebrew_pkg_list:
      - '{{ homebrew_pkg_list }}'
      - 'python@{{ python_exe_suffix }}'
      - python-setuptools
      - virtualenv
      - pyenv-virtualenv

- name: add perl essentials
  set_fact:
    homebrew_pkg_list:
      - '{{ homebrew_pkg_list }}'
      - perl
      - cpanminus
      - libdbi
      - libiodbc

- name: utility packages from homebrew
  set_fact:
    homebrew_pkg_list:
      - '{{ homebrew_pkg_list }}'
      - make
      - libtool
      - lame
      - gnutls
      - 'gnu-sed'
      - curl
      - texinfo
      - texi2html
      - 'font-dejavu'
      - 'font-liberation'

- name: print final list of packages
  debug:
    msg:
      '{{ lookup("flattened", homebrew_pkg_list) }}'

- name: install packages
  become: false
  homebrew:
    name:
      '{{ lookup("flattened", homebrew_pkg_list) }}'


- name: Get mysqlclient libs
  shell:
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:"{{ pkgmgr_prefix }}/opt/mysql-client/lib/pkgconfig/" &&
    {{ pkgmgr_prefix }}/bin/pkg-config --libs mysqlclient
  register: LIBS_OUT

- name: set MYSQLCLIENT_LDFLAGS fact
  set_fact:  MYSQLCLIENT_LDFLAGS={{ LIBS_OUT.stdout }}

- name: Get mysqlclient cflags
  shell:
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:"{{ pkgmgr_prefix }}/opt/mysql-client/lib/pkgconfig/" &&
    {{ pkgmgr_prefix }}/bin/pkg-config --cflags mysqlclient
  register: CFLAG_OUT

- name: set MYSQLCLIENT_CFLAGS fact
  set_fact:  MYSQLCLIENT_CFLAGS={{ CFLAG_OUT.stdout }}

- name: create a list of perl modules
  set_fact:
    cpanm_pkg_list:
      - Date::Manip
      - DateTime::Format::ISO8601
      - Image::Size
      - IO::Socket::INET6
      - JSON
      - LWP
      - HTTP::Request::AsCGI
      - Net::UPnP
      - Net::SSLeay
      - SOAP::Lite
      - XML::XPath
      - XML::Simple
      - FindBin
      - IPC::Cmd

- name: print final list of cpanm packages
  debug:
    msg:
      '{{ lookup("flattened", cpanm_pkg_list) }}'

- name: cpanm - install perl modules
  become: false
  command: cpanm
    --mirror 'http://cpan.cpantesters.org/'
    --force
    {{  cpanm_pkg_list | join(' ')  }}
  ignore_errors: yes
  environment:
    OPENSSL_PREFIX: "{{ pkgmgr_prefix }}/opt/openssl/"

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
