# roles/mythtv/tasks/dnf_centos.yml

---

- name: dnf_centos | Setup RPMFusion repository (CentOS release versions)
  dnf:
    disable_gpg_check: true
    name: '{{ rpmfusion_el_rpm }}'

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=3:
