# roles/mythtv/tasks/dnf_fedora.yml

---

- name: dnf_fedora | Check rpm-free-release
  shell:            /bin/rpm --quiet --query rpmfusion-free-release && echo installed || echo missing  # noqa command-instead-of-module
  register:         rpmfusion

- name: dnf_fedora | Check Rawhide /etc/fedora-release
  shell:            /usr/bin/grep -qi Rawhide /etc/fedora-release && echo rawhide || echo release
  register:         rawhide

- name: dnf_fedora | Enable the RPM Fusion repository
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
    state: present

- name: dnf_fedora | Setup RPMFusion repository (Fedora release versions)
  command:
    cmd: dnf install -y --nogpgcheck {{ rpmfusion_rpm }}
  when:
    - rpmfusion.stdout == "missing"
    - rawhide.stdout == "release"

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=3:
