# roles/mythtv/tasks/main.yml

# Single set of tasks for ALL package managers/distributions/versions.

# Runs any special setup tasks, loads a list of packages plus some for
# Qt5 (or Qt6 if requested) and then install them.

---

- name: Set Single Role for all package managers, distibutions and versions
  set_fact:
    distro: '{{ ansible_distribution | regex_replace("[/ ]", "_") | lower }}'
    version: '{{ ansible_distribution_major_version | int }}'

- name: See if special setup tasks exist
  stat:
    path:  '{{ playbook_dir }}/roles/mythtv/tasks/{{ ansible_pkg_mgr }}_{{ distro }}.yml'
  register: special_stat_results

- name: Run any special setup tasks
  include_tasks:
    file: '{{ ansible_pkg_mgr }}_{{ distro }}.yml'
  when: special_stat_results.stat.exists

- name: 'Load packages for: "{{ distro }}/{{ version }}"'  # noqa name[template]
  include_vars:
    file: '{{ item }}'
  with_first_found:
    - '{{ distro }}/{{ version }}.yml'
    - '{{ distro }}/{{ ansible_distribution_release | lower }}.yml'
    - '{{ distro }}/rolling.yml'
    - missing.yml

- name: Warn the user and end this play
  when: packages is undefined
  block:
    - name: 'Missing package alert: {{ manual_action_text }}'
      debug:
        msg: './roles/mythtv/vars/{{ distro }}/{{ version }}.yml is missing.
        {{ missing_package_message }}: {{ instruction_text }}'

    - name: Ending this play
      meta: end_play

- name: 'Optionally add qt5 packages (the default)'
  set_fact:
    packages:
      - '{{ packages }}'
      - '{{ qt5_packages }}'
  when: (qt6 is undefined or not qt6) and qt5_packages is defined

- name: Optionally add qt6 packages
  set_fact:
    packages:
      - '{{ packages }}'
      - '{{ qt6_packages }}'
  when: qt6 is defined and qt6 and qt6_packages is defined

- name: Flatten package lists
  set_fact:
    packages: '{{ packages | flatten() }}'

- name: Final package list
  debug:
    msg: '{{ packages }}'

- name: Install the packages
  package:
    name: '{{ packages }}'

...

# :!./mythtv.yml -l localhost -e '{"use_old_roles": false}' -e '{"venv_active": true}'
# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2,80:
