# roles/mythtv/tasks/main.yml

# Single set of tasks for all package managers/distributions/versions
# except mac.

# Runs any special setup tasks, loads a list of packages and then install them.

---

- name: Set distro and version values
  set_fact:
    distro: '{{ ansible_distribution | regex_replace("[/ ]", "_") | lower }}'
    version: '{{ ansible_distribution_major_version | int }}'

- name: 'Run any special tasks'
  include_tasks:
    file: '{{ item }}'
  with_first_found:
    - files: '{{ ansible_pkg_mgr }}_{{ distro }}.yml'
      skip: true

- name: Load distribution/version packages.
  include_vars:
    file: '{{ item }}'
  with_first_found:
    - '{{ distro }}/{{ version }}.yml'
    - '{{ distro }}/{{ ansible_distribution_release | lower }}.yml'
    - '{{ distro }}/rolling.yml'
    - '{{ distro }}/{{ ansible_pkg_mgr }}.yml'
    - '{{ distro }}/{{ ansible_distribution_version }}.yml'
    - missing.yml

- name: No package list, warn the user and end this play
  when: packages is undefined
  block:
    - name: 'Unable to find a package: {{ manual_action_text }}'
      debug:
        msg: './roles/mythtv/vars/{{ distro }}/... is missing.
        {{ missing_package_message }}: {{ instruction_text }}'

    - name: Ending this play
      meta: end_play

- name: 'Optionally add qt5 packages (the default)'
  set_fact:
    packages:
      - '{{ packages }}'
      - '{{ qt5_packages }}'
  when: (qt6 is undefined or not qt6) and qt5_packages is defined

- name: Optionally add qt6 packages
  set_fact:
    packages:
      - '{{ packages }}'
      - '{{ qt6_packages }}'
  when: qt6 is defined and qt6 and qt6_packages is defined

- name: Optionally add local_user_packages
  set_fact:
    packages:
      - '{{ packages }}'
      - '{{ local_user_packages }}'
  when: local_user_packages is defined

- name: Flatten the packages list
  ansible.builtin.set_fact:
    packages: '{{ packages | flatten }}'

- name: Final package list
  debug:
    var: packages

- name: Install the packages
  package:
    name: '{{ packages }}'

- name: 'Optionally perform any package manager specific post installation operations'
  include_tasks:
    file: '{{ item }}'
  with_first_found:
    - files: '{{ ansible_pkg_mgr }}_{{ distro }}_post.yml'
      skip: true

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2,80:
