# v16.0 URL:  http://download.opensuse.org/repositories/devel:/languages:/perl/16.0
---

- name: zypper_opensuse_leap | Set Suse repository
  set_fact:
    suse_repo:
      "http://download.opensuse.org/repositories/devel:/languages:/perl"

# Current (8/2022) directory formats:
# 15.4/
# openSUSE_Leap_15.3/

- name: zypper_opensuse_leap | Set Perl repository URL for Leap v1/2/3
  set_fact:
    perl_repo:
      "{{ suse_repo }}/{{ ansible_distribution | regex_replace('\\ ', '_') }}_{{ ansible_distribution_version }}/"
  when: ansible_distribution_major_version | int < 4

- name: zypper_opensuse_leap | Set Perl repository URL for Leap v4+
  set_fact:
    perl_repo:
      "{{ suse_repo }}/{{ ansible_distribution_version }}"
  when: ansible_distribution_major_version | int > 4

- name: zypper_opensuse_leap | Print Perl repository URL
  debug:
    var: perl_repo

- name: zypper_opensuse_leap | Enable devel:languages:perl repository
  zypper_repository:
    name: devel_languages_perl
    repo: '{{ perl_repo }}'
    state: present
    auto_import_keys: true
    runrefresh: true
    autorefresh: true

...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
